version: '3.7'
services:
  web:         
    build: 
      context: .
    command: npm run dev
    container_name: mywebsite 
    ports:
      - "3002:3000"    
    volumes:
      - ./app:/app 
    environment:
      - WATCHPACK_POLLING=true